### ISSUE TITLE
SEO / redirections

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#10]
Il existe a mon avis une bonne tonne de liens pointant vers des URL au format "https://www.afpy.org/jobs/back-end-developer-chez-meltygroup" qui maintenant 404, pourrait-on réparer ça ?

**Comment by liZe** [comment]
C'est théoriquement possible, mais c'est potentiellement long pour une fonctionnalité qui sera de moins en moins utile au fil des nouvelles indexations des moteurs de recherche.

Si des gens sont motivés…

**Comment by JulienPalard** [comment]
Bon j'ai trash fixé ça à la va-vite parce que j'aime pas les 404.

J'ai généré des redirections nginx a coup de sed comme ça, et ça marche :
```
# Pour les news :
grep -o '<id>.*</id>' */post.xml | while read -r line; do printf "location = /%s { return 301 https://www.afpy.org/posts/actualites/%s; }\n" "$(echo "$line" | sed 's|afpy.org/jobs/|afpy.org/news/|g' | cut -d/ -f5,6 | tr -d '<')" "$(echo "$line" | cut -d/ -f1)"; done

# Pour les jobs :
grep -o '<id>.*</id>' */post.xml | while read -r line; do printf "location = "/%s" { return 301 https://www.afpy.org/posts/emplois/%s; }\n" "$(echo "$line" | cut -d/ -f5,6 | tr -d '<')" "$(echo "$line" | cut -d/ -f1)"; done
```

Par exemple maintenant: 

```
$ curl -I 'https://www.afpy.org/jobs/nexedi-Dev ERP5'
HTTP/1.1 301 Moved Permanently
[...]
Location: https://www.afpy.org/posts/emplois/1203373810
[...]
```

La question est : Laisse-on cet ticket ouvert jusqu'a faire plus propre, ou laisse-on ça comme ça et ferme-on le ticket, je suis ouvert aux deux.

**Comment by JulienPalard** [comment]
On dirait que tu as transformé les XML de mon export :
De mon côté j'ai toujours le link href alternate :
```
$ grep -c 'link href' jobs/*.xml | cut -d: -f2 | sort | uniq -c
    146 1
    683 2
```

Server-side, pas toujours :
```
# grep -c '<link href.*alternate' */post.xml | cut -d: -f2 | sort | uniq -c
  23 0
 559 1
```

Ceux qui n'ont pas de alternate semblent récents, c'est dommage, je ne peux pas générer leurs redirections :

```
# grep -L '<link href.*alternate' */post.xml | xargs grep -o '<published.*/published>'
1497432670/post.xml:<published>Wed, 14 Jun 2017 09:31:10 -0000</published>
1499330164/post.xml:<published>Thu, 06 Jul 2017 08:36:04 -0000</published>
1502369242/post.xml:<published>Thu, 10 Aug 2017 12:47:22 -0000</published>
1504014864/post.xml:<published>Tue, 29 Aug 2017 13:54:24 -0000</published>
1506949143/post.xml:<published>Mon, 02 Oct 2017 12:59:03 -0000</published>
1507905621/post.xml:<published>Fri, 13 Oct 2017 14:40:21 -0000</published>
1515684439/post.xml:<published>Thu, 11 Jan 2018 15:27:19 -0000</published>
1516286666/post.xml:<published>Thu, 18 Jan 2018 14:44:26 -0000</published>
1517331762/post.xml:<published>Tue, 30 Jan 2018 17:02:42 -0000</published>
1519829876/post.xml:<published>Wed, 28 Feb 2018 14:57:56 -0000</published>
1520522135/post.xml:<published>Thu, 08 Mar 2018 15:15:35 -0000</published>
1521560550/post.xml:<published>Tue, 20 Mar 2018 15:42:30 -0000</published>
1521730667/post.xml:<published>Thu, 22 Mar 2018 14:57:47 -0000</published>
1522066577/post.xml:<published>Mon, 26 Mar 2018 12:16:17 -0000</published>
1522077851/post.xml:<published>Mon, 26 Mar 2018 15:24:11 -0000</published>
1522142326/post.xml:<published>Tue, 27 Mar 2018 09:18:46 -0000</published>
1522142335/post.xml:<published>Tue, 27 Mar 2018 09:18:55 -0000</published>
1522849556/post.xml:<published>Wed, 04 Apr 2018 13:45:56 -0000</published>
1523353771/post.xml:<published>Tue, 10 Apr 2018 09:49:31 -0000</published>
1523624098/post.xml:<published>Fri, 13 Apr 2018 12:54:58 -0000</published>
1524585206/post.xml:<published>Tue, 24 Apr 2018 15:53:26 -0000</published>
1524746863/post.xml:<published>Thu, 26 Apr 2018 12:47:43 -0000</published>
1525767470/post.xml:<published>Tue, 08 May 2018 08:17:50 -0000</published>
```

C'est réparable ?

Tiens je vois que pour ceux là ce n'est pas du format atom mais le pseudo-format-rss, de mon côté j'ai par exemple : 

```
$ cat jobs/back-end-developer-chez-meltygroup.xml
<?xml version="1.0" encoding="utf8"?>
<entry><title>Back-end developer chez meltygroup</title><link href="https://www.afpy.org/jobs/back-end-developer-chez-meltygroup" rel="alternate"></link>
[...]
```

et server side:

```
head -n 1 1520522135/post.xml
<item><title>Back-end developer chez meltygroup</title><summary>Dans le cadre de la refonte de ses services, meltyLab revoit l'int&#233;gralit&#233; de son infrastructure et recherche un d&#233;veloppeur Back-End pour nous accompagner dans la conception et le d&#233;veloppement de ce projet.</summary>
```

**Comment by liZe** [comment]
> J'ai généré des redirections nginx a coup de sed comme ça, et ça marche :

Bien joué :wow:

> On dirait que tu as transformé les XML de mon export :

Oui, j'ai aménagé certains trucs comme je disais dans #5. Concrètement, les champs qui ne sont pas dans l'interface d'édition ne sont pas enregistrés dans les fichiers lors de l'édition. Ceux où le lien manque sont ceux qui ont été modifiés depuis l'interface.

> C'est réparable ?

Je vais remettre les champs pour les fichiers où ils manquent, mais ils re-disparaîtront quand on les éditera depuis l'interface (sauf si on change l'implémentation pour garder les champs inutilisés).

> Tiens je vois que pour ceux là ce n'est pas du format atom mais le pseudo-format-rss, de mon côté j'ai par exemple :

Oups. J'ai oublié un `item` à la place d'un `entry`, je corrige ça.

**Comment by liZe** [comment]
(Note pour plus tard : le sed de FreeBSD n'est pas celui de Linux.)

**Comment by liZe** [comment]
J'ai remis les liens dans les articles où ils n'y étaient pas. Mon script a pas marché pour 3 articles qui sont dans `trash` et pour le dernier article (qui a été créé depuis le nouveau site).
