### ISSUE TITLE
Jobs dépubliés

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#11]
Environ 800 offres d'emploi ont été dépubliées lors de la migration plone → flask, pourquoi ?

**Comment by liZe** [comment]
Ne trouvant pas le champ qui indique l'état de publication dans les données, j'ai d'abord naïvement mis en ligne toutes les offres, avant de me rendre compte qu'une très grande partie des offres n'étaient pas en ligne sur le Plone. Du coup, j'ai tout mis hors ligne et j'ai remis en ligne les dernières offres acceptées sur le Plone à la main.

Je viens de créer #13 pour avoir accès à l'historique.

**Comment by JulienPalard** [comment]
Je m'en occupe, je peux faire des mv directement sur rainette pour publier / dépublier ?

**Comment by JulienPalard** [comment]
C'est fait, ça fait 576 jobs publiés et 249 non publiés.

**Comment by JulienPalard** [comment]
>Je peux t'envoyer le mot de passe par mail si tu veux.

Oh je me suis crée un compte y'a quelque jours pour aler visiter l'admin þ j'ai pris le login mdk.
