### ISSUE TITLE
Modification d'une offre d'emploi non-publiée

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#14]
Vu qu'il semble impossible pour une offre en attente de publication d'être modifiée par son auteur (le bouton "enregistrer" est "one shot") il faudrait (en attendant que ce soit possible ?) au moins le préciser sur l'interface ? Je voit un article "en cours de rédaction" dans les drafts.

**Comment by liZe** [comment]
Nous avions la volonté de ne pas avoir de comptes personnels et de garder une authentification simple au niveau du serveur HTTP pour les modérateurs. Et sans authentification, c'est moins pratique pour rendre les articles modifiables par l'auteur !

Le préciser sur l'interface me semble une très bonne idée.

**Comment by JulienPalard** [comment]
> Et sans authentification, c'est moins pratique pour rendre les articles modifiables par l'auteur !

Pas forcément, on pourrait générer un "jeton de modification de l'article" au moment de sa création, jeton utilisable pour modifier l'article, jeton qu'on fournirai sous forme d'URL d'édition contenant le jeton.

Typiquement lors de l'enregistrement on pourrait afficher un message du genre :

> Votre annonce est en attente de modération, vous pouvez toujours la modifier en utilisant ce lien https://www.afpy.org/post/edit/emplois/1526037635/token/ohdeingohtei1Sifizoh, attention à conserver ce lien secret.

**Comment by liZe** [comment]
Corrigé par #18.
