### ISSUE TITLE
Ajouter un endpoint pour savoir si il y a des articles / jobs à modérer

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#15]
Un truc simple, pour alain, pour ré-implémenter les notifications sur IRC. J'imagine bien un `/status` qui renverrai quelques informations sur le statut du site:

```
{
    "news" {"drafts": 0, "published": 120, "trash": 4},
    "jobs": {"drafts": 0, "published": 780, "trash": 8},
    "disk_free_GB": 16.2,
    "load_avg": 0.16
}
```

Quelque chose qui nous serve, à nous, à IRC, à nagios, peu importe à avoir en un clin d'œil l'état du site quoi.

**Comment by liZe** [comment]
Fait dans #30 !
