### ISSUE TITLE
Documenter comment on fait une MEP, comment on crée un compte admin, ...

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#16]
Pour créer un compte moi j'utilise :
```
openssl passwd -apr1
```

puis `pwgen 10` (ailleurs) puis vim pour assembler le tout `mdk:{paste_hash_here}` dans `/usr/local/etc/nginx/htpasswd`.

Pour les mise en prod j'sais pas faire, j'imagine que quelqu'un fait un rsync de l'extérieur ? Mais sans --delete pour pas supprimer les posts ? ou avec un --delete mais un bon combo d'ignore pour quand même supprimer les fichier devenu innutils ?

**Comment by Seluj78** [comment]
On peux close cette issue après que https://github.com/AFPy/site/pull/58 soit mergé normalement 🎉 le process sera différent

**Comment by Mindiell** [comment]
Il faudra juste penser à documenter le nouveau process donc ;o)

**Comment by JulienPalard** [comment]
Bon pour faire une MEP c'est easy : git push :D
