### ISSUE TITLE
Quelqu'un a pensé a mettre un secret dans l'env en prod ?

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#21]
Après le merge et la mise en prod de https://github.com/AFPy/site/pull/18 j'ai l'impression que personne n'a mis de SECRET dans l'env, du moins, un procstat -e sur un uwsgi n'en montre pas :(

**Comment by liZe** [comment]
Il est caché dans `/etc/rc.conf` !

**Comment by liZe** [comment]
> hier dans un "ps" il n'y était pas, maintenant il y est, ok :)

Oui, drôle de chose : `ps` tronque la sortie sur la largeur, du coup tu vas le voir ou pas selon la largeur de ton terminal.

**Comment by liZe** [comment]
> Peut être qu'hier soir l'env était bien configuré MAIS que le uwsgi n'était pas redémarré.

Bizarre, j'avais même redémarré avant de faire la mise à jour… Bon, tant que ça y est maintenant…
