### ISSUE TITLE
Fermeture du plone

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#24]
Les actualités et offres d'emplois étant migrés, et puisqu'il semble qu'on ne souhaite pas migrer le reste, je propose qu'on commence doucement à fermer le plone.

Une première étape pourrait simplement être de virer le plone du site_enabled de la jail ḩttp, quelque temps, comme ça si on se dit "ah mais il manque un truc" on y accède facilement.

**Comment by liZe** [comment]
Pour info, j'ai envoyé un message sur la mailing-list du comité directeur, et il m'a entre autres été remonté le fait que certaines infos potentiellement intéressantes était stockées par certains dans des coins perdus du Plone. Nous avons également discuté du forum qui était actif jusqu'à la migration.

Je vais écrire la semaine prochaine sur la mailing list des membres pour avertir de la fermeture imminente de l'ancien site. Si personne ne se manifeste, on pourra le virer du site_enabled la conscience tranquille :smile:.

**Comment by JulienPalard** [comment]
Y'a des gens qui tombent encore sur https://plone.afpy.org/jobs il faudrait fermer le plone et poser des 301.

**Comment by liZe** [comment]
Je me demandais bien à qui pouvait servir ce Plone encore ouvert et j'étais bien résolu à le fermer … jusqu'à qu'on ait besoin de retrouver le règlement intérieur et qu'on soit super content d'en retrouver un vieux sur ce foutu site.

PyConFr serait sans un bon moment pour fermer ce site, ça serait une bonne étape d'un sprint sur la com de l'AFPy.

**Comment by liZe** [comment]
C'est fermé !
