### ISSUE TITLE
Bouton "supprimer"

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#31]
Des utilisateurs (c.f. la ML) souhaiteraient dépublier des offres d'emploi obsolètes depuis le lien d'admin.

La fonctionalité "dépublier" (qui ne leur est pas accessible) ne conviendrait pas : elle remet l'article en "liste d'attente de modération" (`waiting/`), un modérateur passera donc le re-publier (le boulet) (probablement moi) dans les minutes qui suivent.

Je pense qu'une solution serait un bouton "Supprimer", accessible depuis la page d'admin ET la page d'édition (celle avec le jeton), qui déplace l'article dans `trash/` plutôt que `waiting/`.

**Comment by liZe** [comment]
Duplique #8.
