### ISSUE TITLE
Migration du planet

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#4]
Il semble qu'on ai un planet, ici https://plone.afpy.org/planet/, qui est affiché ici : https://www.afpy.org/feed/planet j'imagine qu'on veut le sortir de plone.afpy.org ? 

Qu'est-ce que c'est actuellement ? un planetplanet ? Un module plone ?

**Comment by liZe** [comment]
> Qu'est-ce que c'est actuellement ? un planetplanet ? Un module plone ?

Aucune idée :wink:.

J'ai repris les flux d'origine, sauf celui de CubicWeb dont les articles sont en anglais. J'ai mis un cache de 10 minutes pour éviter de récupérer les flux à chaque fois.
