### ISSUE TITLE
Quand on copie-colle dans le WYSIWYG, la couleur de l'arrière plan et du texte peuvent rester

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#43]
Mais l'éditeur ne permet pas ni d'enlever la couleur de fond ni d'enlever la couleur du texte, on peut donc être "obligés" de publier un article en noir sur blanc si on l'a copié collé (ça vient d'arriver, pour https://www.afpy.org/posts/actualites/1538987685 et j'ai été enlever la couleur avec vim directement dans le XML en prod, youpi).

**Comment by Seluj78** [comment]
On peux close cette issue après que https://github.com/AFPy/site/pull/58 soit mergé normalement 🎉
