### ISSUE TITLE
Fichiers statiques par article

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#47]
Pour https://www.afpy.org/posts/actualites/1576681254 j'ai mis le rapport de transparence ici : `/home/afpy-org/src/static/2019_pyconfr_transparency_report.pdf` sur `deb.afpy.org`.

J'imagine bien qu'a la prochaine migration on va oublier le fichier, c'est clairement pas sa place.

Il faudrait un moyen de poser des fichiers de ce type dans le dossier du post ?

**Comment by Mindiell** [comment]
J'ai corrigé l'erreur induite lors de la dernière modification qui supprimait une image si on enregistrait un article avec une image déjà présente sans y toucher.
J'ai donc également ajouter une notion de fichier joint en plus de l'image.

**Comment by Seluj78** [comment]
On peux close ?
