### ISSUE TITLE
Add me to sentry

### ISSUE THREAD

**Issue by Seluj78** [AFPy/site#49]

**Comment by JulienPalard** [comment]
We'd have to pay sentry to add more users on the project :(

**Comment by Seluj78** [comment]
Who is already a user on the project ? Maybe we can purge some old ones ?

**Comment by JulienPalard** [comment]
I'm alone. I created it myself a few month ago, free plans are for single users.

**Comment by Seluj78** [comment]
😱 I'm sure we can contact sentry and ask them nicely ! 😁

**Comment by Seluj78** [comment]
We could also host our own sentry.

**Comment by JulienPalard** [comment]
Naupe, it's way too big for the AFPy alone (I'm not even sure it's open source). But I bet there exist some lightweight open source alternatives.

**Comment by Seluj78** [comment]
https://github.com/getsentry/onpremise

**Comment by JulienPalard** [comment]
Mouai, overkill je pense.
