### ISSUE TITLE
Migrer les anciens articles

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#5]
URL actuelle des anciens articles : https://zope.afpy.org/news

Actuellement plus ou moins répliqué ici : https://www.afpy.org/feed/planet puisque les *news* de l'ancien site sont exposées en RSS via le planet (qui lui est ici : https://plone.afpy.org/planet/, c.f. https://github.com/AFPy/site/issues/4).

Plusieurs pistes sont ouvertes pour héberger les articles (c.f. mailing list):

- Les intégrer dans le nouveau site en flask
- Ajouter un Pelican
- Je rajouterai ajouter un Django (et faire d'une pierre deux coups avec les offres d'emploi ?)

Il faut aussi penser à les migrer, la solution pour migrer dépendera de la solution pour héberger mais j'imagine que ça se script (je peux m'y coller).

**Comment by liZe** [comment]
Après mûre réflexion, j'ai penché pour la première solution (directement dans le site Flask).

L'idée est de garder un système le plus simple possible, sans gestion de comptes, avec une interface simple permettant de créer des offres d'emploi / actualités et une interface permettant de les valider. Il faut un format simple pour le stockage des articles, qui permet à la fois de migrer l'existant et de créer les nouveaux articles.

Je crois que j'ai trouvé un bon compromis. L'idée est de stocker chaque article dans un dossier dont le nom est un identifiant croissant, avec un fichier `post.jpg` ou `post.png` pour l'image, et un fichier XML largement inspiré de RSS :

```xml
<item>
  <title>
    <![CDATA[
Senior Backend Developer H/F
    ]]>
  </title>
  <link>
    <![CDATA[
https://plone.afpy.org/jobs/senior-backend-developer-h-f
    ]]>
  </link>
  <pubDate>
    Wed, 25 Apr 2018 06:27:00 -0000
  </pubDate>
  <description>
    <![CDATA[
Fort de notre succès en Europe et avec une volonté féroce de devenir une marque mondiale, nous avons beaucoup à faire afin de tenir la roadmap et les montées en charge. Au sein du BOT et plus particulièrement de la Squad Core, ton rôle au quotidien sera de designer &amp; structurer l’architecture du back end. Oui c’est tout… pourquoi faire compliqué quand on peut faire simple ?
    ]]>
  </description>
  <content>
    <![CDATA[
<p><span>CE JOB EST FAIT POUR TOI &amp; TU ES AU BON ENDROIT SI…</span></p>
<p>• Tu es un ingénieur talentueux avec 4 à 8 d’expériences sur un poste similaire<br />• Tu es disponible immédiatement (ou au plus tard en mars 2018 !) <br />• Tu es malin, rigoureux et doté d’une vraie appétence pour le business<br />• Tu souhaites faire de la bonne tech en suivant les bests practices (unit test, intégration en continu…)<br />• Si tu es un expert en Python tout en étant autodidacte et ouvert d’esprit<br />• Si tu optimises/refactores ton code avec un œil critique<br />• Si tu adores la veille et aimes être up-to-date<br />• Si tu adores le team play et le fun <br />• Si tu veux rejoindre un environnement challengeant : AWS, RestFul API, Python, Django, VueJs, Algolia, NewRelic, Jenkins, Docker, Intégration en continue, Agile, SEO (comme vous ne le connaissez pas), Celery, RabbitMQ, ElasticSearch, Nginx, UWSGI, Unit Test</p>
<p>**On papote ?**</p>
<p> </p>
<a target="_blank" href="https://jobs.backmarket.fr/jobs/senior-backend-engineer-squad-core-h-f_paris_BM_Q26Oj0j">Voir l'annonce originale
</a>
    ]]>
  </content>
</item>
```

Générer des fichiers comme celui là semble jouable avec un petit script. @JulienPalard ça te tente ?

J'ai déjà fait les pages listant les articles et la page affichant un article (sur la branche `posts`). Les pages d'ajout et d'édition (dont la validation) sont assez simples à faire, je les ajouterai dans la semaine.

**Comment by JulienPalard** [comment]
Ça sous-entend que les gens vont nous donner des offres d'emploi en HTML ? Je n'y crois pas, et je n'ai pas envie de transcrire des mails en HTML, même simples. Quitte a faire une PR/un push par article / offre d'emploi, quitte à avoir un fichier par article, pourquoi pas les rédiger en markdown avec des entêtes àla Pelican ? Je préfère rédiger du markdown que du HTML. C'est à dire (copié collé de codeenseine.fr) :

```
Title: Atelier du 8 novembre 2017
Date: 2017-10-16 12:01
Modified: 2017-10-16 12:01
Category: Ateliers
Slug: atelier-2017-10-18
Summary: Le prochain atelier Code-en-Seine aura lieu le 8 novembre à 19h

Le prochain [atelier code-en-seine](https://codeenseine.fr/ateliers-code-en-seine.html) se déroulera le 8 novembre 2017 de 19h à 21h.

Inscriptions : [https://events.cri-paris.org/e/123/code-en-seine](https://events.cri-paris.org/e/123/code-en-seine)
```

Qui donne : https://codeenseine.fr/atelier-2017-10-18.html

**Comment by liZe** [comment]
> Ça sous-entend que les gens vont nous donner des offres d'emploi en HTML ?

Pas du tout, heureusement :smile:.

C'est le formulaire de création et d'édition des articles qui contient un éditeur WYSIWYG. J'ai déjà fait ça plein de fois, c'est encore plus simple que de taper du Markdown.

**Comment by JulienPalard** [comment]
> une interface permettant de les valider


> L'idée est de stocker chaque article dans un dossier dont le nom est un identifiant croissant

Je comprend que le fichier devra contenir l'information "publié ou non" / "modéré ou non", tu veux donc créer une "base de donnée minimaliste à base de dossiers et de fichiers" ?

**Comment by liZe** [comment]
> Je comprend que le fichier devra contenir l'information "publié ou non" / "modéré ou non"

On a juste un statut « publié » qui peut être changé par le modérateur.

> tu veux donc créer une "base de donnée minimaliste à base de dossiers et de fichiers" ?

C'est un bien grand concept pour parler de fichiers structurés mis dans des dossiers et des sous-dossiers :smile:. C'est ce que font les gestionnaires de contenus sans bases de données (type Pelican ou Lektor en Python, ou Jekyll en Ruby).

J'ai déjà fait la partie publique et j'ai bientôt fini l'ajout et l'édition d'articles. Il me restera juste la page de modération.

**Comment by JulienPalard** [comment]
> J'ai déjà fait la partie publique et j'ai bientôt fini l'ajout et l'édition d'articles. Il me restera juste la page de modération.

OK. Je m'occupe (pas dans la journée) de l'extraction des articles.

**Comment by JulienPalard** [comment]
Hop, "petit" script d'extraction finit : https://github.com/JulienPalard/extract_of_afpy_articles

J'ai essayé de respecter Atom (https://tools.ietf.org/html/rfc4287#section-4.1.2) au maximum, puisqu'il autorise un "stand-alone Atom Entry Document" ça correspond bien à ce que tu disais, et atom autorisant les attributs supplémentaires, j'ai pu aussi y glisser les métadonnées des jobs (compagny, address, phone, ...).

Dis moi si tu vois des soucis à l'usage.

**Comment by liZe** [comment]
> Dis moi si tu vois des soucis à l'usage.

C'est parfait, merci !

J'étais parti sur du RSS parce que les flux dont je m'étais inspiré étaient du RSS, mais utiliser Atom et son *stand-alone entry document* est une bonne idée. J'ai aménagé deux ou trois trucs, mais globalement ça ne posait pas de problème.

Il reste encore deux ou trois trucs à régler (dont les images), mais j'ai migré les articles sans tarder pour éviter que d'autres articles soient créés sur l'ancienne plateforme. Je posterai un message sur la mailing-list demain !
