### ISSUE TITLE
500 on posts and 404 on posts/

### ISSUE THREAD

**Issue by Seluj78** [AFPy/site#50]
https://afpy.org/posts
https://afpy.org/posts/

I've found it to be linked to this view

https://github.com/AFPy/site/blob/32c5c2d846c6d8eecc3c167256bb66d2a3580c1b/afpy.py#L79-L86

It seems that this catches the GET `posts/` first and aborts with a 404. And the 500 happens when the `posts` template is rendered through this view and it doesn't have the correct variables

**Comment by Mindiell** [comment]
What would be the expected action ? 
- Go back to homepage ?
- Display a "posts" page (to create) enabling links to "actualités" and "emplois" ?
- Something else ?

**Comment by Seluj78** [comment]
On peux close cette issue après que https://github.com/AFPy/site/pull/58 soit mergé normalement 🎉

**Comment by Mindiell** [comment]
On a bien un 404 sur les 2 URL, à clore.

**Comment by Mindiell** [comment]
On peut close !
