### ISSUE TITLE
Problème de nom de domaine dans les liens externes

### ISSUE THREAD

**Issue by liZe** [AFPy/site#52]
Les liens externes générés pour les fichiers RSS utilisent `_external`, qui récupère le nom de domaine courant. Comme le site est servi à la fois sur `www.afpy.org` et sur `afpy.org`, on a théoriquement des liens avec `www` sur le site `www`, et sans `www` sur le site sans `www`. Malheureusement, ces fichiers sont mis en cache, ce qui fait qu’on a des liens avec ou sans sur les deux sites, selon si la dernière version en cache a été faite sur l’un ou sur l’autre.

Cela cause des changements aléatoires des liens dans les flux, et mettent donc les articles comme modifiés dans certains lecteurs de flux. Autrement dit : c’est relou :smile:.

Est-il envisageable de servir le site uniquement avec ou sans le `www`, avec une redirection ?

**Comment by JulienPalard** [comment]
Ma todo list :
```
$ git log -S '301 afpy.org → www.afpy.org'
commit f4f3aeefbdaf389a8c7029b4feef0e309a361b3d
Author: Julien Palard <julien@palard.fr>
Date:   Mon Dec 23 23:38:47 2019 +0100
```

en effet, va faloir que je me réveille :)

**Comment by liZe** [comment]
> en effet, va faloir que je me réveille :)

Pas d’urgence, j’arrive à vivre sans :p.

**Comment by JulienPalard** [comment]
C'est en prod.
```
$ curl -I https://afpy.org | grep Location
Location: https://www.afpy.org/

$ curl -I http://afpy.org | grep Location
Location: https://www.afpy.org/

$ curl -I http://www.afpy.org | grep Location
Location: https://www.afpy.org/


```

**Comment by JulienPalard** [comment]
SIGDODO

**Comment by liZe** [comment]
❤️ 💤
