### ISSUE TITLE
Ajouter un lien vers le Discourse

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#53]
Je pense que le site devrait pointer un petit ou un gros lien vers https://discuss.afpy.org.

J'ai aucune idée de comment faire ça de manière ergonomique, comptez pas sur moi :]

**Comment by JulienPalard** [comment]
J'ai mis en prod ta proposition, mais je trouve ça un peu étrange de mettre le lien du discuss hors de la page "discussion".

Mais peut être qu'avoir communauté et discussion séparé c'est peut être pas une bonne idée ?

Je suis assez nul en UX mais j'ai une idée (laulles) : si on supprime la page discussion, qu'on rajoute discuss et IRC dans la page communauté ? La ligne qui parle d'IRC pourraît être très courte, avec juste "on est sur #python-fr et sur #afpy sur freenode" et sur les deux salons un lien qui pointerai vers une page contenant l'iframe kiwiirc ?

**Comment by Mindiell** [comment]
J'avoue n'avoir vu la page discussion que bien plus tard. C'est, en effet (AMHA) assez étrange de séparer les deux. Mêe si je comprends bien le côté communauté physique et le côté discussions en ligne.
Je vais voir si je peux basculer sur la page discussion, au moins pour conserver la philosophie de l'existant...

**Comment by Seluj78** [comment]
On peux close ?

**Comment by JulienPalard** [comment]
Non, il n'y a toujours pas de lien vers le discuss depuis la page discussion : https://www.afpy.org/discussion

**Comment by Mindiell** [comment]
Travail fait, avec un peu de retard sur l'horaire prévu ;)
