### ISSUE TITLE
Ajouter le contenu des articles dnas le flux RSS

### ISSUE THREAD

**Issue by Mindiell** [AFPy/site#70]
A l'heure actuelle, le flux RSS est assez pauvre : pas de contenu, pas d'auteur, pas de tags. Il serait intéerssant d'y inclure au moins le contenu des articles (ou des annonces pour le flux jobs).

Idéalement ajouter un auteur (s'il y a des comptes ou bien forcer à Afpy ?) et des tags (si besoin)...

**Comment by JulienPalard** [comment]
J'ai redirigé les flux RSS du site sur les flux RSS du Discourse, plus riche en contenu et en métadonnée.

J'ai aussi migré les offres d'emploi sur le Discourse.
