### ISSUE TITLE
Admin modérateur

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#80]
Dans le nouveau site je ne voit pas comment trouver les job à modérer, j'ai du le faire via sqlite :

    sqlite> update jobpost set state = 'published' dt_published = '2021-07-23 08:22:01.047373' where id  = 1316;

Attention, sans le dt_published, ça fait une jolie 500.

**Comment by Mindiell** [comment]
Dans l'adinistration ,à droite, tu as un bouton "Moderate". Cela t'affiche une page où tu choisis si tu veux modérer les actus ou les jobs. En cliquant sur "moderate jobs", tu tombes sur la liste des jobs à modérer.

**Comment by JulienPalard** [comment]
Ooooooohhh c'est mieux qu'éditer le job à la main et faire planter le site :D

La dernière fois j'avais trouvé le job à modéré dans l'admin du modèle job, mais ça ne met pas à jour automatiquement dt_published donc boom encore une 500 :D

**Comment by JulienPalard** [comment]
Bon bah je ferme l'issue alors :D
